### ISSUE TITLE
＜感染シミュゲ　制作進行案（仮）＞

### ISSUE THREAD

**Issue by ES-Yukun** [ES-Yukun/2021AS-U22#1]
■制作期限
・U22提出期限　8月31日

・制作期限　8月13日

■定期集会

■担当項目　

・佐藤
「ぷ」数値のパラメーター化
「で」ゲーム画面
・池田
「ぷ」線グラフの実装？
・岸田
「ぷ」
「し」機能具体案、初期数値
・宮田
「ぷ」ワクチン、変異株

・未定
「ぷ」シーンの追加、複数選択、カウント、外出規制
「し」
「で」使用画像、グラフデザイン、画面構成
「お」概要などなど

＊ぷ＝プログラム、し＝進行、で＝デザイン、お＝応募用紙内容

■応募用紙内容

作品名

作品名ふりがな

作品ジャンル

制作背景（制作目的含む）

作品概要

作品のアピールポイント・工夫点

**Comment by kisiitu** [comment]
＜感染シミュゲ　制作進行案（仮）＞

■制作期限
・U22提出期限　8月31日

・制作期限　8月13日

■定期集会？
・３日または１週間に一回？（必要なら臨時も）
・ZoomまたはLINEにて行う
・石黒先生への定期報告もこの時にできたら、

＊それぞれの予定は要確認

■担当項目？

・佐藤
「ぷ」数値のパラメーター化
「で」ゲーム画面
・池田
「ぷ」線グラフの実装？
・岸田
「ぷ」
「し」機能具体案、初期数値
・宮田
「ぷ」ワクチン、変異株

・未定
「ぷ」シーンの追加、複数選択、カウント、外出規制
「し」
「で」使用画像、グラフデザイン、画面構成
「お」概要などなど

＊ぷ＝プログラム、し＝進行、で＝デザイン、お＝応募用紙内容

■応募用紙内容？

・作品名

・作品名ふりがな

・作品ジャンル

・制作背景（制作目的含む）

・作品概要

・作品のアピールポイント・工夫点


＊これもそれぞれで分担して考える

**Comment by kisiitu** [comment]
＜内容案No,３＞感染シミュレーションゲーム

■目指す作品の形

コロナの現状の深刻さを伝えられるリアルな数字を用いたシミュレーションゲーム
基本としては時間の経過による感染の拡大に対してプレイヤーが感染対策やワクチンなどで感染を抑えたり感染者を治療するのを主軸とする
また、APIによる現在の日本の感染者数などをゲームの内容に生かしていきたい


■ゲームの終わり

ゲームクリア：感染者の根絶（positive＿count＝＝100）
ゲームオーバー：全員感染（negative ＿count＝＝0）または時間切れ（time＝＝0）
　

■ 採用する外部情報(APIも含め)
[API]
・感染者数(人口との比率で最初の感染者の人数を決める)
・ワクチン摂取人数(ゲームとの比較用)
・復帰人数(ゲームとの比較用)

[サイト]
・人口(初期感染比率設定用)
・人口密度(初期人数決定用)

＊全て県ごとの情報とする


■プレイヤーのできること

先生はボタンを押して何かイベントを起こすのがいいのではとのこと
クリックとかキーボードとか

一人一人だと効率悪いので複数に対して効果発動（PCのホームでできる範囲選択とか？）

↑これはできるかどうか検証（使用変数　選択状態されているかの真偽、this.myno、xy）

	元の案	追加案	ボツ案
ワクチン←（名称変えたほうがいいかも注射とか）	指定範囲の人に摂取させ感染している人は％で治り（negative がpositiveになる）、してない人は感染しにくくなる（infectivityの減少）	・時間経過で元に戻る（使用変数 カウント、immunity）	・すでに感染している人に対しては半々の確率で元に戻す（使用変数 ランダム数、this.status）
変異種	一定時間経過で感染力の強いー感染力％の高いーウイルスがでてくる（使用変数 game.flame、infectivity）		・ウイルスも一つのクラスとして感染者が不定期に生成する
時間経過で速度やサイズが変わったり、効果のあるワクチン（ワクチンにも種類を増やす）が違うのを出す
どれが効くのかもステータスで表す（使用変数 this.r、this.w、ワクチン）
外出規制	簡単なのは動かなくなるだけ
	・当たり判定もなくせば変化が分かりやすくなるやも（intersectをなくす）	・壁を作るなら壁クラスで選択された人オブジェの周囲に配置する、または線を引いたところが壁になる
・衝突判定については少し前の授業で習ったものでいけそう


余裕あれば追加、、

**Comment by guriru2222** [comment]
[都道府県別人口＆人口密度表.txt](https://github.com/ES-Yukun/2021AS-U22/files/6856013/default.txt)
そのままコメントとして書いたら非常に読みづらくなる気がしたので
ファイルとして落とさせてもらいます
データのソースは　https://uub.jp/rnk/p_j.html

**Comment by koike-moyashi** [comment]
> [都道府県別人口＆人口密度表.txt](https://github.com/ES-Yukun/2021AS-U22/files/6856013/default.txt)

ご存知かもしれませんがjson化してプログラムからアクセスする手法を書いておきます。

カンマ区切りのcsvにしてからjson化して、下記の２つの方法（他にもありますが、簡単な方法を紹介）でプログラムから使えます。

## json化
### csv化
`aaa,bbb,ccc`みたいなカンマ区切りのデータにする。
1. VSコードで上記テキストのタブを,に置換する（Ctrl+Fで置換。空白部分をコピペで上部にペースト）
2. 余計なスペースや,,を綺麗にする
   ,,を置換で１つに（,,→,）。半角スペースの削除。これも置換で（ →なし）
3. 上部の`人口,人口密度`を消して、`pref,population,density`等にする
### json化
1. https://www.site24x7.com/ja/tools/csv-to-json.html の左側にペースト。
2. 右側のjsonをコピペで取得。

## javascriptから読み取る
今回は多分 方法２の方が簡単かと思います。

### 方法1 （httpサーバ経由で読み取る）
1. ↑のデータをpopulatoin.jsonとかのファイルにして htmlと一緒の場所に入れておく。
2. jsonをプログラムから使うのは、前に「enchantjs 05 他のJavaScriptと組み合わせる」でやった取得のサンプルと一緒です。$.getJSON({ url: population.json}).done....みたいな感じ。

※こちらは**VSCodeのLiveServerを起動して**それ経由で読み取る必要があります（前に画像認識サンプルを動かした方法）。

### 方法2（JavaScriptとして読み取る）
1. jsonファイルを下記のように加工（１行目に`var population_data = `を挿入）してpopulation.jsとかで保存。
```
var population_data = 
[
    {
        "pref" : "三重県",
        "population" : "20",
        "density": "100"
    },
    {
        "pref" : "愛知県",
        "population" : "30",
         "density": "200"
    }
 ];
```
2. headに下記のように書く
```
<script type="text/javascript" src="popuration.js"></script>
````
3. 下記のようにアクセス
```
console.log(population_data);
```
